### ISSUE TITLE
Not showing audio track

### ISSUE THREAD

**Issue by sgtstadanko** [Saoneth/plex-custom-audio#10]
THis is great. I am on linux and have run against mka file but the track doesnt show up in the track selection on the play settings screen. Am i missing something? Process completed in less than a second:

root@thor /u/l/plexmediaserver# ./Plex\ Custom\ Audio\ Mapper  /media/store/4k/The\ Shining\ \(1980\)/
2
Cleaning up old audio records
Selected directories for scanning:
 - /media/store/4k/The Shining (1980)/
Scanning library for new audio files...
Processing: /media/store/4k/The Shining (1980)/The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-EPSiLON.mkv

**Comment by luigi311** [comment]
Running into the same issue

**Comment by luigi311** [comment]
Looks like its only an issue with mka. I tried it with a ac3 file and it detected it and heres the output
```
# ./Plex\ Custom\ Audio\ Mapper "/data/Movies/Hercules (2014)"
2
Cleaning up old audio records
Selected directories for scanning:
 - /data/Movies/Hercules (2014)
Scanning library for new audio files...
Processing: /data/Movies/Hercules (2014)/Hercules (2014) Remux-1080p.mkv
 - found audio file: /data/Movies/Hercules (2014)/Hercules (2014) Remux-1080p.eng.stereo-drc.ac3
[ac3 @ 0xd5dd40] Format ac3 detected only with low score of 1, misdetection possible!
[ac3 @ 0xd5dd40] Estimating duration from bitrate, this may be inaccurate
    - forcing language: eng
    - forcing title: stereo-drc
    @ bitrate: 512000
    @ <nil> 2 491300 file:///data/Movies/Hercules (2014)/Hercules (2014) Remux-1080p.eng.stereo-drc.ac3 eac3 eng 2021-01-12 11:30:06 2021-01-12 11:30:06 1000 712583 2 512000 0 0 0 ma%3AaudioChannelLayout=stereo&ma%3AsamplingRate=32000
    - added successfully
    ```

**Comment by sgtstadanko** [comment]
ok went with a mp3 i converted to ac3 with audacity and got the following:

```
Selected directories for scanning:
 - /media/store/video/Krull (1983)/
Scanning library for new audio files...
Processing: /media/store/video/Krull (1983)/Krull.mkv
 - found audio file: /media/store/video/Krull (1983)/Krull.eng.ac3
[ac3 @ 0x258f7c0] Estimating duration from bitrate, this may be inaccurate
    - forcing language: eng
    @ bitrate: 320000
    @ <nil> 2 37918 file:///media/store/video/Krull (1983)/Krull.eng.ac3 ac3 eng 2021-01-14 20:10:10 2021-01-14 20:10:10 1000 37930 2 320000 0 0 0 ma%3AaudioChannelLayout=stereo&ma%3AsamplingRate=44100
    - added successfully
```


So i can see the track now (YAY!) but when i try and play movie with that selected I get:

```
Jan 14, 2021 20:10:38.590 [0x7fece9ffb700] ERROR - [Transcoder] Stream specifier ':1000' in filtergraph description [0:1000] aresample=async=1:ocl='stereo':rematrix_maxval=0.000000dB:osr=44100[0] matches no streams.
Jan 14, 2021 20:10:53.005 [0x7feda5ffb700] ERROR - [Transcoder] Stream specifier ':1000' in filtergraph description [0:1000] aresample=async=1:ocl='stereo':rematrix_maxval=0.000000dB:osr=44100[0] matches no streams.
Jan 14, 2021 20:11:18.193 [0x7fece97fa700] ERROR - [Transcoder] Stream specifier ':1000' in filtergraph description [0:1000] aresample=async=1:ocl='stereo':rematrix_maxval=0.000000dB:osr=44100[0] matches no streams.
```

With the web player in Chrome it just crashes the transcoder.  I have also been able to select in the mobile app and while it doesnt crash, there is no sound.

Any ideas?

**Comment by sgtstadanko** [comment]
Ok after some poking around the code, i realized that you are installing a custom/different Transcoder package.  I have updated my plex a few times since installing and it must have overwritten what you changed!  Once i re-installed it just worked! yay!

However, this did answer my question in that it only plays the track of whats in the file. Its doesnt mix/remux it in with the original audio. To do that will require ripping the audio from the movie and adding the commentary track to it and then exporting it back it out.

**Comment by Saoneth** [comment]
Audio track codec doesn't really matter, you can just change extension if it doesn't catch .mka for you  - which is weird as it's on the list (maybe it's case sensitive?).

Custom transcoder is of course manditory for all of this to work, and original one should be in the same directory with _org suffix.
Also it's necessary for it to actually run, so if there are problems with playback you can try disabling direct play.
