### ISSUE TITLE
unknown tokenizer: collating

### ISSUE THREAD

**Issue by alexeynl** [Saoneth/plex-custom-audio#11]
I get an error trying to execute command

sudo docker exec plex "/usr/lib/plexmediaserver/Plex Custom Audio Mapper":

Cleaning up old audio records
Scanning library for new audio files...
2021/04/09 16:02:36 unknown tokenizer: collating

**Comment by Saoneth** [comment]
This is because of some new triggers added in plex. The solution to this is to:
* remove these triggers
* run audio mapper
* add these triggers back

Here's post explaining how to do this manually: https://forums.plex.tv/t/can-no-longer-update-library-database-with-sqlite3/701405/49

**Comment by Saoneth** [comment]
It's fixed in new release. It's done in this ugly way described above, but to do it properly, we'd have to compile go-sqlite3 with icu extension and I just couldn't make it work ;c

**Comment by soyelmismo** [comment]
```
Scanning library for new audio files...
2023/09/12 01:49:31 unknown tokenizer: collating
```
