### ISSUE TITLE
Problem transcoding

### ISSUE THREAD

**Issue by tomerwis** [Saoneth/plex-custom-audio#2]
Thanks for releasing this plugin. I tried it on the latest Plex for Windows 10 and after mapping the audios and replacing the original transcoder with your Plex Transcoder I'm getting the following error:

Playback Error
Conversion failed. The transcoder exited due to an error.

I might be doing something wrong or it's not working on the latest Plex 1.18.9.2578

**Comment by Windendless** [comment]
try this: https://github.com/Windendless/plex-custom-audio/commit/5c2b9d43fa96a6e9e7f22400e896ab53b9da1fa7

**Comment by Saoneth** [comment]
Thanks for your intrest in this project. As i'm using linux for my plex server i kind of forgot about windows nuances (like .exe extension), so it's no wonder it doesn't work.

@Windendless do you mind creating pull-request with your fixes?

**Comment by Windendless** [comment]
of course not.

**Comment by Eselter** [comment]
Any new when new build will be available? On windows transcoder still doesn't work :/

**Comment by Eselter** [comment]
I build transcoder with windows fix but still doesn't work :/

**Comment by Saoneth** [comment]
Fixed in v1.1.0
