### ISSUE TITLE
Not work transcoding

### ISSUE THREAD

**Issue by Un1QExit** [Saoneth/plex-custom-audio#4]
Hi, i try install plex-custom-audio in unraid vs plex ver. 1.19.1.2645 (linuxserver/plex repository)
On guide command did not work. I changed:

2. `cd /usr/lib/plexmediaplayer` to `cd /usr/lib/plexmediaserver/`
my docker conteiner has no folder *player

3. `curl https://raw.githubusercontent.com/Saoneth/plex-custom-audio/master/install.sh | sudo bash`
to 
`curl https://raw.githubusercontent.com/Saoneth/plex-custom-audio/master/install.sh | bash`
my console write me - `sudo: command not found`

4 and 5. For check i use only one folder `./Plex\ Custom\ Audio\ Mapper "/Anime TV/Clockwork Planet/"`

![console](https://user-images.githubusercontent.com/63778748/79433303-9acb5580-7fd5-11ea-92cc-f72ef58d36d9.jpg)
![Naming](https://user-images.githubusercontent.com/63778748/79433306-9b63ec00-7fd5-11ea-9ec0-4621c0430ac1.jpg)

Then when starting a video in plex i have no changes i have only one sound on mkv conteiner(japan). i cant select my ext audio(ru.mka)
What am I doing wrong, plz help me.

thx.

**Comment by qnorsten** [comment]
I had the same problem as you. Using plexserver on linux and windows client to fix. 
It wouldn't detect the mka file unless I renamed it to .ac3. And then the transcoder would crash. 
I built the version from here https://github.com/Saoneth/plex-custom-audio/pull/3 .

After that it works perfectly for me.

**Comment by Saoneth** [comment]
There was missing .mka on extension list. It should be fine now.
