### ISSUE TITLE
Doesn't see mka file on windows

### ISSUE THREAD

**Issue by frontez** [Saoneth/plex-custom-audio#5]
I am using Windows. I tried to add "mka" audio file into a movie but it seems that Plex Custom Audio Mapper cannot recognize it, when I renamed the file into "ac3" format it sees, but in that case Plex cannot convert the audio...

**Comment by luigi311** [comment]
looks like #3 might fix your issue.

**Comment by Saoneth** [comment]
Fixed in v1.1.0
