### ISSUE TITLE
Question does it remux or does it keep the video file untouched ?

### ISSUE THREAD

**Issue by TRaSH-** [Saoneth/plex-custom-audio#6]
being that the plex topic has been closed for this script,
I would like to know what it does exactly
For example i got a movie named:
`Movie.2008.1080p.BluRay.DTS.x264.mkv`
and i would add a audio file in to the same location called
`Movie.2008.1080p.BluRay.DTS.x264.dut.mka`
would it then remux the audio file in to the original file or hopefully i won't and i will just get finally the option to choose the dutch audio file in this example.

**Comment by mdstoll** [comment]
I believe the idea is that it keeps two seperate files in your folder, but allows you to select the music stream for playback. 

It essentially writes a link in the Plex database, pointing to the additional audio file.

**Comment by Saoneth** [comment]
It leaves files untouched and transcodes them on the fly. Like when you have avi but your device doesn't support it, so plex transcodes it. If audio and video codecs are supported, then it should only transcode container, which isn't that much resource intensive.
