### ISSUE TITLE
Audio visible but not playing

### ISSUE THREAD

**Issue by mdstoll** [Saoneth/plex-custom-audio#7]
Thanks for creating this plugin! Will keep it short but this could really solve me a headache!

My setup:
[VPS Debian running PMS] > [Shield running Plex] > TV [Arc] > Soundbar
Original video files are MKV 4K with multiple audio and subtitle streams. The idea is that everything should direct stream (as transcoding 4K will fade the image).

Normal playback works (audio files within MKV container). 

I managed to add separate media files such as ac3 / aac to plex by means of your script. I can see and select them in plex, but when I select them, there is no sound (if i play these files directly, they play sound). I read the file needs to be 'mka', however when I 'convert' to mka your script doesn't recognize the mka extension. Therefore, it isn't added to the playback options.

If you need more details, let me know.

**Comment by Saoneth** [comment]
Do you still have this issue? Direct playback should be disabled when using this, so plex runs transcoder which adds audio track on the fly. This shouldn't do anything else if your deviece supports codecs and you have quality set to Maximum.
