### ISSUE TITLE
BASENAME.TRACK_TITLE.LANG.EXT

### ISSUE THREAD

**Issue by Andrysky** [Saoneth/plex-custom-audio#8]
i need to recognize BASENAME.**TRACK_TITLE**.**LANG**.EXT
i found the code section in mapper.go  
https://github.com/Saoneth/plex-custom-audio/blob/bd44176e87208dd6bf1363daf2da0edb0256f811/cmd/Plex%20Custom%20Audio%20Mapper/mapper.go#L257

but I can't find where the language recognition is happening?
 where is it printed? -  ! invalid language: 
i get the following

Processing: ...../Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC]/Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC].mkv
 - found audio file: ...../Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC]/Ext Audio/Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC].Gavrilov.rus.ac3
    ! invalid language: Gavrilov
 - found audio file: ......./Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC]/Ext Audio/Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC].Kinomania.rus.ac3
    ! invalid language: Kinomania

**Comment by Saoneth** [comment]
File name should be in this format:  BASENAME.LANG.TRACK_TITLE.EXT, so it should be:

> Kiki's Delivery Service [BD-rip 1920x1080 x264 FLAC].rus.Gavrilov.ac3

**Comment by Andrysky** [comment]
@Saoneth reopen please, can help please, I can't find where the language recognition is happening?
where is it printed? - ` ! invalid language: `

**Comment by Saoneth** [comment]
@Andrysky It's here: https://github.com/Saoneth/plex-custom-audio/blob/bd44176e87208dd6bf1363daf2da0edb0256f811/cmd/Plex%20Custom%20Audio%20Mapper/mapper.go#L255-L265

but you're using old version from github releases.

**Comment by Saoneth** [comment]
Wrong language doesn't prevent adding track in latest release.
