### ISSUE TITLE
Why is it required for the [index] column to be set to 1000+?

### ISSUE THREAD

**Issue by Lionhunter3k** [Saoneth/plex-custom-audio#9]
From what I see, if the [index] column is set to null, Plex will treat it as an external resource, and if it's set to 1000, it will not. However, setting to 1000 makes the Windows Plex Player think it's stream #1000 inside the file, from what I can understand from the logs.

```

update [media_streams] set [codec] = "aac",
[bitrate] = 320000,
[index] = null, //or 1000
[extra_data] = "ma%3Aprofile=lc&ma%3ArequiredBandwidths=320%2C320%2C320%2C320%2C320%2C320%2C320%2C320&ma%3AsamplingRate=48000&ma%3Atitle=English%3A%205%2E1ch"
where [id] = 5325
```

Thanks!

**Comment by Saoneth** [comment]
Great find. I tried to make it work and it detects it as external audio track, but when I start it there is no sound :(
It also crashes on web player.

Current solution sets it to stream 1000, so custom transcoder knows it should be replaced. This should work on windows plex player if you installed custom transcoder correctly.
